### ISSUE TITLE
Using `makeChoice` in `sequence-panel`

### ISSUE THREAD

**Issue by bulbil** [digirati-co-uk/iiif-canvas-panel#246]
- Choice is not always updated even if supplying `makeChoice` with valid choice ids -- possibly to do with sequence index, as in only the right page or sequence index `1`, or maybe which ever is loaded last?
- With multiple annotation pages, how to propagate the `choice` to the correct annotation page?

https://github.com/digirati-co-uk/iiif-canvas-panel/pull/245 More info in the PR, but ultimately I believe there is ambiguity around what exactly the `makeChoice` is being applied to depending on current state of the panel.

**Comment by stephenwf** [comment]
Yes you're right. This seems like a race condition (although it might be deterministic). If there are more than once choice, the `makeChoice` is overridden directly.

The same is true for Annotation Page manager

https://github.com/digirati-co-uk/iiif-canvas-panel/blob/0cfa8f9402842d3e12127259a4e98eb9fdc45ac4/packages/canvas-panel/src/components/ViewCanvas/ViewCanvas.tsx#L44-L58

This binds the `makeChoice` and `annotationPageManager` directly on the web component as APIs. 

So our options:
- Hoist this up, so there is a single `makeChoice` implementation that will call `makeChoice` for all visible canvases
- Change how the choices are stored, instead of using React state, move to Vault meta.


The second option would be ideal I think. At the moment, the choices that are selected are stored here:
https://github.com/digirati-co-uk/react-iiif-vault/blob/main/src/hooks/usePaintables.ts#L15


However, you can store associated data with resource in Vault, that aren't part of the resource itself and then subscribe to changes to them. This is how the styling of annotations works


There are 2 APIs:
```ts
vault.setMetaValue([ id, 'NAME', scope ], value);
```

and
```ts
vault.getResourceMeta(id, 'NAME');
```

So for example, you could do:
```ts
vault.setMetaValue([ id, 'EXAMPLE', 'choice-a' ], true);
vault.setMetaValue([ id, 'EXAMPLE', 'choice-b' ], false);
```

and then elsewhere:
```ts
vault.getMetaValue(id, 'EXAMPLE'); // { 'choice-a': true, 'choice-b': false };
```

Inside RIV, there is an API to make these reactive and listen for changes:
```ts
const choices = useVaultSelector((state, vault) => {
  return vault.getMetaValue(id, 'EXAMPLE');
}, [ id, /* Also reset when values here change, e.g. an ID */ ]);
```

The benefit of putting this inside the vault, is we could change `makeChoice()` to just talk to the Vault instance instead. You could also make choices before anything is rendered, and also make choices for pages that aren't visible yet - and have them persist across pages.

The simple example I made didn't store any metadata about the choices though, but.. you can always do: `vault.get(id);` to resolve the label/metadata for the choice item. 

I've not yet had an idea on how to make the AnnotationPageManager work like this, that might have to be a different API. There are other complications (like annotation target) that makes it a bit more tricky for sequences.

**Comment by stephenwf** [comment]
Some other workaround ideas, for getting a quicker fix:

```ts
const originalMakeChoice = (el as any).makeChoice;

(el as any).makeChoice = (id: string, options: any) => { 
   if (actions.current) { 
     actions.current.makeChoice(id, options); 
   }
   if (originalMakeChoice) originalMakeChoice(id, options);
 }; 
```

We could stack the make choice calls. HOWEVER the makeChoice implementation would have to be changed/wrapped to ignore inputs that don't match the available choices. So if an option  like: `{ deselectOthers: true }` is passed, it doesn't reset _all_ other choices to their default state.

**Comment by stephenwf** [comment]
With #247 merged and in `@digirati/canvas-panel-web-components@1.0.62` can this now be closed? We could look at handling multi-choice in sequence panel with its own API later, so its easier to get a picture of _all_ available choices grouped by image - but the individual events should have enough information for now.

**Comment by abrin** [comment]
I think we can close this. We've got one bug we're starting to chase down if you have N > 1 choices on a single canvas you only get one, but we can open a separate ticket -- we're looking into that now.  But, maybe that's what you mean by 'multi-choice'?
